version: '1'
services:
  usvs_container:
    image: usvs_no_payment
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    command: python3 -u visa_reschedule.py --config config.yaml
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
